### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by LytexWZ** [StealthIQ/Bluestrike#4]
![Screenshot_2024-04-19-14-55-41-660_com termux](https://github.com/StealthIQ/Bluestrike/assets/72569213/cd6e691c-c34a-4af0-9642-1ead0fdd4f23)

Trying to install on termux, after running the command paru -Sy --noconfirm --needed bluez bluez-utils I tried to use the tool but gave an empty directory error, trying to run it again gives the error of command not found, any solutions? Or it is not supported on termux

**Comment by Hacker3030** [comment]
I think there is typo error in the command. Command must be something like this:
`pacman -Sy --noconfirm --needed bluez bluez-utils`

"Pacman" you must use I think on termux. Linux I'll see........

Hope this helps 😁🙂

**Comment by LytexWZ** [comment]
New errors dropped :( 
![Uploading Screenshot_2024-04-24-17-52-33-364_com.termux.jpg…]()

**Comment by LytexWZ** [comment]
New errors dropped :(
![Screenshot_2024-04-24-17-52-33-364_com termux](https://github.com/StealthIQ/Bluestrike/assets/72569213/c1b91cbc-3e70-41cc-8caf-759d84abf28a)

**Comment by Hacker3030** [comment]
See the error says that the `pacman` Authorization key had not been initialized so follow in this manner:
`apt update`
`pacman-key --init`
`pacman -Sy --noconfirm --needed bluez bluez-utils`

Try and see 😉.

**Comment by StealthIQ** [comment]
Hey @Hacker3030 , thanks for the assist. So, about tmux, you mentioned it's in pacman, but here's the thing: I'm not entirely sure it'll fly smoothly on tmux. It was originally made for Arch Linux, and I haven't given it a whirl on any other distros.

Anyway @LytexWZ lmk if the issue has been resolved I will help out while I can.
